# Constantes Agrupamento
FORMATO_DATA = "%m/%Y"
NUM_REGISTROS_PROXIMOS = 200
MIN_REGISTROS_VALIDOS = 30
MAX_FATOR_ESCALA = 10
INCREMENTO_FATOR_ESCALA = 0.25

# Constantes Média Móvel
NUM_PERIODOS = 6
MIN_PERIODOS = 6

# Constantes DEA V2
DEA_INPUT_COLS = [
    'CNES_SALAS',
    'CNES_LEITOS_SUS',
    'HORAS_MEDICOS',
    'HORAS_ENFERMAGEM',
]
DEA_OUTPUT_COL = 'SIA_SIH_VALOR'
DEA_VIRTUAL_INPUT_MIN_RESTRICTIONS = {
    'CNES_SALAS': 0.09, 
    'CNES_LEITOS_SUS': 0.16,
    'HORAS_MEDICOS': 0.16, 
    'HORAS_ENFERMAGEM': 0.09
}

# Colunas para cálculo de distância no agrupamento
COLS_DISTANCIA_CLUSTER = ['HORAS_MEDICOS', 'CNES_LEITOS_SUS']

cols_dea = ['SIA_SIH_VALOR', 'CNES_SALAS', 'CNES_LEITOS_SUS', 'HORAS_MEDICOS', 'HORAS_ENFERMAGEM']

dict_nomes = {
    'COMPETEN' : 'Mês',
    'CNES_SALAS': 'Salas',
    'CNES_CENTROS_CIRURGICOS': 'Centros\nCirúrgicos',
    'CNES_LEITOS_SUS': 'Leitos\nSUS',
    'CNES_MEDICOS': 'Médicos',
    'HORAS_MEDICOS': 'Horas\nMédicos',
    'CNES_PROFISSIONAIS_ENFERMAGEM': 'Profissionais\nEnfermagem',
    'HORAS_ENFERMAGEM': 'Horas\nEnfermagem',
    'SIH_VALOR': 'SIH',
    'SIA_VALOR': 'SIA',
    'SIA_SIH_VALOR': 'Produção\nTotal'
}

data_dict = { # Tabela SIGTAP
    'SIA-0101': 'Ações coletivas/individuais em saúde',
    'SIA-0102': 'Vigilância em saúde',
    'SIA-0201': 'Coleta de material',
    'SIA-0202': 'Diagnóstico em laboratório clínico',
    'SIA-0203': 'Diagnóstico por anatomia patológica e citopatologia',
    'SIA-0204': 'Diagnóstico por radiologia',
    'SIA-0205': 'Diagnóstico por ultrassonografia',
    'SIA-0206': 'Diagnóstico por tomografia',
    'SIA-0207': 'Diagnóstico por ressonância magnética',
    'SIA-0208': 'Diagnóstico por medicina nuclear in vivo',
    'SIA-0209': 'Diagnóstico por endoscopia',
    'SIA-0210': 'Diagnóstico por radiologia intervencionista',
    'SIA-0211': 'Métodos diagnósticos em especialidades',
    'SIA-0212': 'Diagnóstico e procedimentos especiais em hemoterapia',
    'SIA-0213': 'Diagnóstico em vigilância epidemiológica e ambiental',
    'SIA-0214': 'Diagnóstico por teste rápido',
    'SIA-0301': 'Consultas, Atendimentos, Acompanhamentos',
    'SIA-0302': 'Fisioterapia',
    'SIA-0303': 'Tratamentos clínicos (outras especialidades)',
    'SIA-0304': 'Tratamento em oncologia',
    'SIA-0305': 'Tratamento em nefrologia',
    'SIA-0306': 'Hemoterapia',
    'SIA-0307': 'Tratamentos odontológicos',
    'SIA-0308': 'Tratamento de lesões, envenenamentos e outros, decorrentes de causas externas',
    'SIA-0309': 'Terapias especializadas',
    'SIA-0310': 'Parto e nascimento',
    'SIA-0311': 'Cuidados Paliativos',
    'SIA-0401': 'Pequenas cirurgias e cirurgias de pele, tecido subcutâneo e mucosa',
    'SIA-0402': 'Cirurgia de glândulas endócrinas',
    'SIA-0403': 'Cirurgia do sistema nervoso central e periférico',
    'SIA-0404': 'Cirurgia das vias aéreas superiores, da face, da cabeça e do pescoço',
    'SIA-0405': 'Cirurgia do aparelho da visão',
    'SIA-0406': 'Cirurgia do aparelho circulatório',
    'SIA-0407': 'Cirurgia do aparelho digestivo, órgãos anexos e parede abdominal',
    'SIA-0408': 'Cirurgia do sistema osteomuscular',
    'SIA-0409': 'Cirurgia do aparelho geniturinário',
    'SIA-0410': 'Cirurgia de mama',
    'SIA-0411': 'Cirurgia obstétrica',
    'SIA-0412': 'Cirurgia torácica',
    'SIA-0413': 'Cirurgia reparadora',
    'SIA-0414': 'Bucomaxilofacial',
    'SIA-0415': 'Outras cirurgias',
    'SIA-0416': 'Cirurgia em oncologia',
    'SIA-0417': 'Anestesiologia',
    'SIA-0418': 'Cirurgia em nefrologia',
    'SIA-0501': 'Coleta e exames para fins de doação de órgãos, tecidos e células e de transplante',
    'SIA-0502': 'Avaliação de morte encefálica',
    'SIA-0503': 'Ações relacionadas à doação de órgãos e tecidos para transplante',
    'SIA-0504': 'Processamento de tecidos para transplante',
    'SIA-0505': 'Transplante de órgãos, tecidos e células',
    'SIA-0506': 'Acompanhamento e intercorrências no pré e pós-transplante',
    'SIA-0601': 'Medicamentos de dispensação excepcional',
    'SIA-0602': 'Medicamentos estratégicos',
    'SIA-0603': 'Medicamentos de âmbito hospitalar e urgência',
    'SIA-0604': 'Componente Especializado da Assistência Farmacêutica',
    'SIA-0701': 'Órteses, próteses e materiais especiais não relacionados ao ato cirúrgico',
    'SIA-0702': 'Órteses, próteses e materiais especiais relacionados ao ato cirúrgico',
    'SIA-0801': 'Ações relacionadas ao estabelecimento',
    'SIA-0802': 'Ações relacionadas ao atendimento',
    'SIA-0803': 'Autorização, Regulação',
    'SIA-0901': 'Atenção em Oncologia',
    'SIA-0902': 'Atenção em Cardiologia',
    'SIA-0903': 'Atenção em Ortopedia',
    'SIA-0904': 'Atenção em Otorrinolaringologia',
    'SIA-0905': 'Atenção em Oftalmologia',
    'SIA-0906': 'Atenção em Saúde Mulher',
    'SIH-0101': 'Ações coletivas/individuais em saúde',
    'SIH-0102': 'Vigilância em saúde',
    'SIH-0201': 'Coleta de material',
    'SIH-0202': 'Diagnóstico em laboratório clínico',
    'SIH-0203': 'Diagnóstico por anatomia patológica e citopatologia',
    'SIH-0204': 'Diagnóstico por radiologia',
    'SIH-0205': 'Diagnóstico por ultrassonografia',
    'SIH-0206': 'Diagnóstico por tomografia',
    'SIH-0207': 'Diagnóstico por ressonância magnética',
    'SIH-0208': 'Diagnóstico por medicina nuclear in vivo',
    'SIH-0209': 'Diagnóstico por endoscopia',
    'SIH-0210': 'Diagnóstico por radiologia intervencionista',
    'SIH-0211': 'Métodos diagnósticos em especialidades',
    'SIH-0212': 'Diagnóstico e procedimentos especiais em hemoterapia',
    'SIH-0213': 'Diagnóstico em vigilância epidemiológica e ambiental',
    'SIH-0214': 'Diagnóstico por teste rápido',
    'SIH-0301': 'Consultas, Atendimentos, Acompanhamentos',
    'SIH-0302': 'Fisioterapia',
    'SIH-0303': 'Tratamentos clínicos (outras especialidades)',
    'SIH-0304': 'Tratamento em oncologia',
    'SIH-0305': 'Tratamento em nefrologia',
    'SIH-0306': 'Hemoterapia',
    'SIH-0307': 'Tratamentos odontológicos',
    'SIH-0308': 'Tratamento de lesões, envenenamentos e outros, decorrentes de causas externas',
    'SIH-0309': 'Terapias especializadas',
    'SIH-0310': 'Parto e nascimento',
    'SIH-0311': 'Cuidados Paliativos',
    'SIH-0401': 'Pequenas cirurgias e cirurgias de pele, tecido subcutâneo e mucosa',
    'SIH-0402': 'Cirurgia de glândulas endócrinas',
    'SIH-0403': 'Cirurgia do sistema nervoso central e periférico',
    'SIH-0404': 'Cirurgia das vias aéreas superiores, da face, da cabeça e do pescoço',
    'SIH-0405': 'Cirurgia do aparelho da visão',
    'SIH-0406': 'Cirurgia do aparelho circulatório',
    'SIH-0407': 'Cirurgia do aparelho digestivo, órgãos anexos e parede abdominal',
    'SIH-0408': 'Cirurgia do sistema osteomuscular',
    'SIH-0409': 'Cirurgia do aparelho geniturinário',
    'SIH-0410': 'Cirurgia de mama',
    'SIH-0411': 'Cirurgia obstétrica',
    'SIH-0412': 'Cirurgia torácica',
    'SIH-0413': 'Cirurgia reparadora',
    'SIH-0414': 'Bucomaxilofacial',
    'SIH-0415': 'Outras cirurgias',
    'SIH-0416': 'Cirurgia em oncologia',
    'SIH-0417': 'Anestesiologia',
    'SIH-0418': 'Cirurgia em nefrologia',
    'SIH-0501': 'Coleta e exames para fins de doação de órgãos, tecidos e células e de transplante',
    'SIH-0502': 'Avaliação de morte encefálica',
    'SIH-0503': 'Ações relacionadas à doação de órgãos e tecidos para transplante',
    'SIH-0504': 'Processamento de tecidos para transplante',
    'SIH-0505': 'Transplante de órgãos, tecidos e células',
    'SIH-0506': 'Acompanhamento e intercorrências no pré e pós-transplante',
    'SIH-0601': 'Medicamentos de dispensação excepcional',
    'SIH-0602': 'Medicamentos estratégicos',
    'SIH-0603': 'Medicamentos de âmbito hospitalar e urgência',
    'SIH-0604': 'Componente Especializado da Assistência Farmacêutica',
    'SIH-0701': 'Órteses, próteses e materiais especiais não relacionados ao ato cirúrgico',
    'SIH-0702': 'Órteses, próteses e materiais especiais relacionados ao ato cirúrgico',
    'SIH-0801': 'Ações relacionadas ao estabelecimento',
    'SIH-0802': 'Ações relacionadas ao atendimento',
    'SIH-0803': 'Autorização / Regulação',
    'SIH-0901': 'Atenção em Oncologia',
    'SIH-0902': 'Atenção em Cardiologia',
    'SIH-0903': 'Atenção em Ortopedia',
    'SIH-0904': 'Atenção em Otorrinolaringologia',
    'SIA-0905': 'Atenção em Oftalmologia',
    'SIA-0906': 'Atenção em Saúde Mulher'
}

cols_sia     =   [  'SIA-0101','SIA-0102',
                    'SIA-0201','SIA-0202','SIA-0203','SIA-0204','SIA-0205',
                    'SIA-0206','SIA-0207','SIA-0208','SIA-0209','SIA-0210',
                    'SIA-0211','SIA-0212','SIA-0213','SIA-0214',
                    'SIA-0301','SIA-0302','SIA-0303','SIA-0304','SIA-0305',
                    'SIA-0306','SIA-0307','SIA-0308','SIA-0309','SIA-0310',
                    'SIA-0311',
                    'SIA-0401','SIA-0402','SIA-0403','SIA-0404','SIA-0405',
                    'SIA-0406','SIA-0407','SIA-0408','SIA-0409','SIA-0410',
                    'SIA-0411','SIA-0412','SIA-0413','SIA-0414','SIA-0415',
                    'SIA-0416','SIA-0417','SIA-0418',
                    'SIA-0501','SIA-0502','SIA-0503','SIA-0504','SIA-0505',
                    'SIA-0506',
                    'SIA-0601','SIA-0602','SIA-0603','SIA-0604',
                    'SIA-0701','SIA-0702','SIA-0801',
                    'SIA-0802','SIA-0803',
                    'SIA-0901','SIA-0902','SIA-0903','SIA-0904','SIA-0905','SIA-0906' ] 

cols_sia_p   =   [  'SIA-0101_p','SIA-0102_p',
                    'SIA-0201_p','SIA-0202_p','SIA-0203_p','SIA-0204_p','SIA-0205_p',
                    'SIA-0206_p','SIA-0207_p','SIA-0208_p','SIA-0209_p','SIA-0210_p',
                    'SIA-0211_p','SIA-0212_p','SIA-0213_p','SIA-0214_p',
                    'SIA-0301_p','SIA-0302_p','SIA-0303_p','SIA-0304_p','SIA-0305_p',
                    'SIA-0306_p','SIA-0307_p','SIA-0308_p','SIA-0309_p','SIA-0310_p',
                    'SIA-0311_p',
                    'SIA-0401_p','SIA-0402_p','SIA-0403_p','SIA-0404_p','SIA-0405_p',
                    'SIA-0406_p','SIA-0407_p','SIA-0408_p','SIA-0409_p','SIA-0410_p',
                    'SIA-0411_p','SIA-0412_p','SIA-0413_p','SIA-0414_p','SIA-0415_p',
                    'SIA-0416_p','SIA-0417_p','SIA-0418_p',
                    'SIA-0501_p','SIA-0502_p','SIA-0503_p','SIA-0504_p','SIA-0505_p',
                    'SIA-0506_p',
                    'SIA-0601_p','SIA-0602_p','SIA-0603_p','SIA-0604_p',
                    'SIA-0701_p','SIA-0702_p','SIA-0801_p',
                    'SIA-0802_p','SIA-0803_p',
                    'SIA-0901_p','SIA-0902_p','SIA-0903_p','SIA-0904_p','SIA-0905_p','SIA-0906_p' ] 

cols_sih =       [  'SIH-0101','SIH-0102',
                    'SIH-0201','SIH-0202','SIH-0203','SIH-0204','SIH-0205',
                    'SIH-0206','SIH-0207','SIH-0208','SIH-0209','SIH-0210',
                    'SIH-0211','SIH-0212','SIH-0213','SIH-0214',
                    'SIH-0301','SIH-0302','SIH-0303','SIH-0304','SIH-0305',
                    'SIH-0306','SIH-0307','SIH-0308','SIH-0309','SIH-0310',
                    'SIH-0311',
                    'SIH-0401','SIH-0402','SIH-0403','SIH-0404','SIH-0405',
                    'SIH-0406','SIH-0407','SIH-0408','SIH-0409','SIH-0410',
                    'SIH-0411','SIH-0412','SIH-0413','SIH-0414','SIH-0415',
                    'SIH-0416','SIH-0417','SIH-0418',
                    'SIH-0501','SIH-0502','SIH-0503','SIH-0504','SIH-0505',
                    'SIH-0506',
                    'SIH-0601','SIH-0602','SIH-0603','SIH-0604',
                    'SIH-0701','SIH-0702','SIH-0801',
                    'SIH-0802','SIH-0803',
                    'SIH-0901','SIH-0902','SIH-0903','SIH-0904','SIH-0905','SIH-0906']

cols_sih_p =     [  'SIH-0101_p','SIH-0102_p',
                    'SIH-0201_p','SIH-0202_p','SIH-0203_p','SIH-0204_p','SIH-0205_p',
                    'SIH-0206_p','SIH-0207_p','SIH-0208_p','SIH-0209_p','SIH-0210_p',
                    'SIH-0211_p','SIH-0212_p','SIH-0213_p','SIH-0214_p',
                    'SIH-0301_p','SIH-0302_p','SIH-0303_p','SIH-0304_p','SIH-0305_p',
                    'SIH-0306_p','SIH-0307_p','SIH-0308_p','SIH-0309_p','SIH-0310_p',
                    'SIH-0311_p',
                    'SIH-0401_p','SIH-0402_p','SIH-0403_p','SIH-0404_p','SIH-0405_p',
                    'SIH-0406_p','SIH-0407_p','SIH-0408_p','SIH-0409_p','SIH-0410_p',
                    'SIH-0411_p','SIH-0412_p','SIH-0413_p','SIH-0414_p','SIH-0415_p',
                    'SIH-0416_p','SIH-0417_p','SIH-0418_p',
                    'SIH-0501_p','SIH-0502_p','SIH-0503_p','SIH-0504_p','SIH-0505_p',
                    'SIH-0506_p',
                    'SIH-0601_p','SIH-0602_p','SIH-0603_p','SIH-0604_p',
                    'SIH-0701_p','SIH-0702_p','SIH-0801_p',
                    'SIH-0802_p','SIH-0803_p',
                    'SIH-0901_p','SIH-0902_p','SIH-0903_p','SIH-0904_p','SIH-0905_p','SIH-0906_p']

cols_base =   ['CNES_SALAS', 
               'CNES_CENTROS_CIRURGICOS',
               'CNES_LEITOS',
               'CNES_LEITOS_SUS', 
               'CNES_MEDICOS', 
               'HORAS_MEDICOS',
               'CNES_PROFISSIONAIS_ENFERMAGEM',
               'HORAS_ENFERMAGEM', 
               'SIH_VALOR', 
               'SIA_VALOR',
               'SIA_SIH_VALOR']

cols_header = [    'CNES', 
                   'COMPETEN',
                   'DESCESTAB', 
                   'GESTAO', 
                   'ATIVIDADE_ENSINO', 
                   'TIPO_UNIDADE', 
                   'FILANTROPICO', 
                   'SE_GERIDA_OSS', 
                   'NAT_JURIDICA', 
                   'ESFERA_FEDERATIVA', 
                   'TIPO_ADMIN_PUB', 'NAT_JURIDICA_SIMPLIFICADA', 
                   'Complexidade_Ambulatorial',
                   'Complexidade_Hospitalar',
                   'UF', 
                   'REGIAO',
                   'MUNICIPIO',
                   'COD_IBGE',
                   'FAIXA_LEITOS']

colunas_cluster = ['Cluster', 
                   'n', 
                   'f', 
                   'COMPETEN', 
                   'CNES', 
                   'DESCESTAB', 
                   'GESTAO', 
                   'ATIVIDADE_ENSINO', 
                   'TIPO_UNIDADE', 
                   'FILANTROPICO', 
                   'SE_GERIDA_OSS', 
                   'NAT_JURIDICA', 
                   'ESFERA_FEDERATIVA', 
                   'TIPO_ADMIN_PUB', 'NAT_JURIDICA_SIMPLIFICADA', 
                   'Complexidade_Ambulatorial',
                   'Complexidade_Hospitalar',
                   'UF', 
                   'REGIAO', 
                   'MUNICIPIO',
                   'COD_IBGE',
                   'FAIXA_LEITOS']+ cols_base + ['Distancia_Ref']

cols_cluster = cols_sia + cols_sih

# Criar um dicionário de alertas
alertas_dict2 = {
    'Alerta_1': 'O hospital possui médicos cuja carga horária é superior à carga horária de 95% dos médicos da mesma especialidade (cirurgião cardíaco, anestesiologista, etc.) e superior a 44 horas.',
    'Alerta_2': 'A carga horária dos médicos cuja carga horária é superior à carga horária de 95% dos médicos da mesma especialidade supera 10% da carga horária dos médicos do hospital.',
    'Alerta_3': 'A carga horária dos médicos cuja carga horária é superior à carga horária de 95% dos médicos da mesma especialidade supera 20% da carga horária dos médicos do hospital.',
    'Alerta_4': 'A carga horária dos médicos cuja carga horária é superior à carga horária de 95% dos médicos da mesma especialidade supera 30% da carga horária dos médicos do hospital.',
    'Alerta_5': 'O hospital possui profissionais de enfermagem cuja carga horária é superior à carga horária de 95% dos profissionais de enfermagem.',
    'Alerta_6': 'A carga horária dos profissionais de enfermagem cuja carga horária é superior à carga horária de 95% dos profissionais de enfermagem supera 10% da carga horária dos profissionais de enfermagem do hospital.',
    'Alerta_7': 'A carga horária dos profissionais de enfermagem cuja carga horária é superior à carga horária de 95% dos profissionais de enfermagem supera 20% da carga horária dos profissionais de enfermagem do hospital.',
    'Alerta_8': 'A carga horária dos profissionais de enfermagem cuja carga horária é superior à carga horária de 95% dos profissionais de enfermagem  supera 30% da carga horária dos profissionais de enfermagem do hospital.',
    'Alerta_9': 'A relação médicos/profissionais de enfermagem do hospital é superior à essa relação de 95% dos demais hospitais.',
    'Alerta_10': 'A relação profissionais de enfermagem/médicos do hospital é superior à essa relação de 95% dos demais hospitais.',
    'Alerta_11': 'A relação profissionais de enfermagem/leitos do hospital é superior à essa relação de 95% dos demais hospitais.',
    'Alerta_12': 'A relação leitos/profissionais de enfermagem é superior à essa relação de 95% dos demais hospitais.',
    'Alerta_13': 'A relação médicos/salas cirúrgicas é superior à essa relação de 95% dos demais hospitais.',
    'Alerta_14': 'A relação salas cirúrgicas/médicos é superior à essa relação de 95% dos demais hospitais.',
    'Alerta_15': 'O hospital possui menos leitos SUS do que leitos totais.',
    'Alerta_16': 'A relação leitos do hospital analisado/leitos dos hospitais benchmark é, em alguns casos, maior do que 4.',
    'Alerta_17': 'A relação leitos do hospital analisado/leitos dos hospitais benchmark é, em alguns casos, menor do que 1/4.',
    'Alerta_18': 'A relação salas cirúrgicas do hospital analisado/salas cirúrgicas dos hospitais benchmark é, em alguns casos, maior do que 4.',
    'Alerta_19': 'A relação salas cirúrgicas do hospital analisado/salas cirúrgicas dos hospitais benchmark é, em alguns casos, menor do que 1/4.',
    'Alerta_20': 'A relação médicos do hospital analisado/médicos dos hospitais benchmark é, em alguns casos, maior do que 4.',
    'Alerta_21': 'A relação médicos do hospital analisado/médicos dos hospitais benchmark é, em alguns casos, menor do que 1/4.',
    'Alerta_22': 'A relação profissionais de enfermagem do hospital analisado/ profissionais de enfermagem dos hospitais benchmark é, em alguns casos, maior do que 4.',
    'Alerta_23': 'A relação profissionais de enfermagem do hospital analisado/ profissionais de enfermagem dos hospitais benchmark é, em alguns casos, menor do que 1/4.',
    'Alerta_24': 'A relação distância euclideana de hospital benchmark/produção do hospital em análise é a 60%.',
    'Alerta_25': 'A relação distância euclideana de hospital benchmark/produção do hospital em análise é, em alguns casos, superior a 75%.',
    'Alerta_26': 'A relação distância euclideana de hospital benchmark/produção do hospital em análise é, em alguns casos, superior a 90%.'
}


alertas_dict = {
    'Alerta_1': "Há médicos no hospital cuja carga horária total (soma da carga horária em todos os hospitais em que o médico trabalha) é superior a 44 horas semanais e superior à de 95% dos médicos da mesma especialidade (A1).",
    'Alerta_2': "Mais de 10% da carga horária total dos médicos do hospital é realizada por médicos que trabalham mais do que 95% dos seus pares de especialidade (A2).",
    'Alerta_3': "Mais de 20% da carga horária total dos médicos do hospital é realizada por médicos que trabalham mais do que 95% dos seus pares de especialidade (A3).",
    'Alerta_4': "Mais de 30% da carga horária total dos médicos do hospital é realizada por médicos que trabalham mais do que 95% dos seus pares de especialidade (A4).",
    'Alerta_5': "Há profissionais de enfermagem no hospital cuja carga horária total (soma da carga horária em todos os hospitais em que o profissional trabalha) é superior a 44 horas semanais e superior à de 95% dos profissionais de enfermagem (A5).",
    'Alerta_6': "Mais de 10% da carga horária total dos profissionais de enfermagem do hospital é realizada por aqueles que trabalham mais do que 95% dos seus pares (A6).",
    'Alerta_7': "Mais de 20% da carga horária total dos profissionais de enfermagem do hospital é realizada por aqueles que trabalham mais do que 95% dos seus pares (A7).",
    'Alerta_8': "Mais de 30% da carga horária total dos profissionais de enfermagem do hospital é realizada por aqueles que trabalham mais do que 95% dos seus pares (A8).",
    'Alerta_9': "A proporção de médicos para profissionais de enfermagem no hospital supera essa mesma proporção em 95% dos demais hospitais (A9).",
    'Alerta_10': "A proporção de profissionais de enfermagem para médicos no hospital supera essa mesma proporção em 95% dos demais hospitais (A10).",
    'Alerta_11': "A proporção de profissionais de enfermagem por leito no hospital é maior do que em 95% dos outros hospitais (A11).",
    'Alerta_12': "A proporção de leitos por profissional de enfermagem no hospital é maior do que em 95% dos outros hospitais (A12).",
    'Alerta_13': "A proporção de médicos para salas cirúrgicas no hospital supera essa mesma proporção em 95% dos demais hospitais (A13).",
    'Alerta_14': "A proporção de salas cirúrgicas para médicos no hospital supera essa mesma proporção em 95% dos demais hospitais (A14).",
    'Alerta_15': "O hospital possui um número de leitos SUS inferior ao total de leitos disponíveis (A15).",
    'Alerta_16': "A relação entre os leitos do hospital analisado e os leitos dos hospitais de referência é, em alguns casos, maior que 4 (A16).",
    'Alerta_17': "A relação entre os leitos do hospital analisado e os leitos dos hospitais de referência é, em alguns casos, menor que 1/4 (A17).",
    'Alerta_18': "A relação entre as salas cirúrgicas do hospital analisado e as salas cirúrgicas dos hospitais de referência é, em alguns casos, maior que 4 (A18).",
    'Alerta_19': "A relação entre as salas cirúrgicas do hospital analisado e as salas cirúrgicas dos hospitais de referência é, em alguns casos, menor que 1/4 (A19).",
    'Alerta_20': "A relação entre os médicos do hospital analisado e os médicos dos hospitais de referência é, em alguns casos, maior que 4 (A20).",
    'Alerta_21': "A relação entre os médicos do hospital analisado e os médicos dos hospitais de referência é, em alguns casos, menor que 1/4 (A21).",
    'Alerta_22': "A relação entre os profissionais de enfermagem do hospital analisado e os profissionais de enfermagem dos hospitais de referência é, em alguns casos, maior que 4 (A22).",
    'Alerta_23': "A relação entre os profissionais de enfermagem do hospital analisado e os profissionais de enfermagem dos hospitais de referência é, em alguns casos, menor que 1/4 (A23).",
    'Alerta_24': "A relação entre distância euclidiana do hospital de referência e a produção do hospital em análise é superior a 60% (A24).",
    'Alerta_25': "A relação entre distância euclidiana do hospital de referência e a produção do hospital em análise é superior a 75% (A25).",
    'Alerta_26': "A relação entre distância euclidiana do hospital de referência e a produção do hospital em análise é superior a 90% (A26).",
}

MIN_VALOR_POSITIVO = 0.01

